@host = localhost:8001

// Not providing this header or using 'web' performs cookie based authentication.
// Using anything else performs token based authentication.
@x_requested_by = mobile

@auth_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBfdG9rZW4iOiJjemRtV2xaRGRYbE1RMGxOV0VweGNsaEllVTVFTWpneGExQkZhV2ROWkRCek1HdDRhMFoyY2pKemMxZHJiVEpWVjBFMU9UTTJkbTVTT1RGYVptNDVjRWRuWld4WmFGWkRXbEpWTFU0MVUwMVlhRVp1UjFFIn0.FrRmY8HnvopMWp4lCjUR-oKV68aKhMw_xT0nCh6_PoM

### Register a new user
POST http://{{host}}/api/user/register/
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "email": "john@test.com",
  "password": "Pass1234!"
}

### Login a user - Cookie based
POST http://{{host}}/api/user/login/
Content-Type: application/json

{
  "email": "john@test.com",
  "password": "Pass1234!"
}

### Login a user - Token based
POST http://{{host}}/api/user/login/
Content-Type: application/json
X-Requested-By: {{x_requested_by}}

{
  "email": "john@test.com",
  "password": "Pass1234!",
  "code": 476466
}

### Request magic link
POST http://{{host}}/api/user/magic_link/request/
Content-Type: application/json

{
  "email": "john@test.com"
}

### Login with magic link
POST http://{{host}}/api/user/magic_link/consume/
Content-Type: application/json

{
  "token": "z3B0kmbVsTRFi8-ZooMib-nOA1hid7Z6irjTLqnF6IcFt_7iwQhpS3KdA3Zw1NyNH80fvKyPkxQL8OX1AZcnfA",
  "code": 808592
}

### Verify email
@verify_email_token = CxiNvxmOP0qbEO4Q5pEKLgJIByFGGCk_T1iu33aiHgZstcNjYmepU3yK
POST http://{{host}}/api/user/verify_email/
Content-Type: application/json

{
  "token": "{{verify_email_token}}"
}

### Get all active sessions
GET http://{{host}}/api/user/active_sessions/
Authorization: {{auth_token}}
X-Requested-By: {{x_requested_by}}

### Close session
POST http://{{host}}/api/user/active_sessions/close/
Content-Type: application/json
Authorization: {{auth_token}}
X-Requested-By: {{x_requested_by}}

{
  "id": "0b20f88d-c41b-4b69-b1dc-cfa2b4d81045"
}

### Get user profile
GET http://{{host}}/api/user/me/
Authorization: {{auth_token}}
X-Requested-By: {{x_requested_by}}

### Logout a user
POST http://{{host}}/api/user/logout/
Authorization: {{auth_token}}
X-Requested-By: {{x_requested_by}}


### TOTP

### Initialize TOTP
POST http://{{host}}/api/user/totp/init/
Authorization: {{auth_token}}
X-Requested-By: {{x_requested_by}}

### Enable TOTP
POST http://{{host}}/api/user/totp/enable/
Content-Type: application/json
Authorization: {{auth_token}}
X-Requested-By: {{x_requested_by}}

{
  "code": 789644
}

### Disable TOTP
PUT http://{{host}}/api/user/totp/disable/
Content-Type: application/json
Authorization: {{auth_token}}
X-Requested-By: {{x_requested_by}}

{
  "code": 155982
}

### Reset backup codes
POST http://{{host}}/api/user/totp/new-backup-codes/
Content-Type: application/json
Authorization: {{auth_token}}
X-Requested-By: {{x_requested_by}}

{
  "code": 899245
}
